// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebook/ent/dialect/sql/schema"
	"github.com/facebook/ent/schema/field"
)

var (
	// TestsColumns holds the columns for the "tests" table.
	TestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "field1", Type: field.TypeBool},
		{Name: "field2", Type: field.TypeFloat64},
		{Name: "field3", Type: field.TypeInt32},
	}
	// TestsTable holds the schema information for the "tests" table.
	TestsTable = &schema.Table{
		Name:        "tests",
		Columns:     TestsColumns,
		PrimaryKey:  []*schema.Column{TestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TestsTable,
	}
)

func init() {
}
