// Code generated by entc, DO NOT EDIT.

package ent

import (
	"align/ent/predicate"
	"align/ent/test"
	"context"
	"fmt"
	"sync"

	"github.com/facebook/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeTest = "Test"
)

// TestMutation represents an operation that mutate the Tests
// nodes in the graph.
type TestMutation struct {
	config
	op            Op
	typ           string
	id            *int
	field1        *bool
	field2        *float64
	addfield2     *float64
	field3        *int32
	addfield3     *int32
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Test, error)
	predicates    []predicate.Test
}

var _ ent.Mutation = (*TestMutation)(nil)

// testOption allows to manage the mutation configuration using functional options.
type testOption func(*TestMutation)

// newTestMutation creates new mutation for Test.
func newTestMutation(c config, op Op, opts ...testOption) *TestMutation {
	m := &TestMutation{
		config:        c,
		op:            op,
		typ:           TypeTest,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTestID sets the id field of the mutation.
func withTestID(id int) testOption {
	return func(m *TestMutation) {
		var (
			err   error
			once  sync.Once
			value *Test
		)
		m.oldValue = func(ctx context.Context) (*Test, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Test.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTest sets the old Test of the mutation.
func withTest(node *Test) testOption {
	return func(m *TestMutation) {
		m.oldValue = func(context.Context) (*Test, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TestMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TestMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *TestMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetField1 sets the field1 field.
func (m *TestMutation) SetField1(b bool) {
	m.field1 = &b
}

// Field1 returns the field1 value in the mutation.
func (m *TestMutation) Field1() (r bool, exists bool) {
	v := m.field1
	if v == nil {
		return
	}
	return *v, true
}

// OldField1 returns the old field1 value of the Test.
// If the Test object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *TestMutation) OldField1(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldField1 is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldField1 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldField1: %w", err)
	}
	return oldValue.Field1, nil
}

// ResetField1 reset all changes of the "field1" field.
func (m *TestMutation) ResetField1() {
	m.field1 = nil
}

// SetField2 sets the field2 field.
func (m *TestMutation) SetField2(f float64) {
	m.field2 = &f
	m.addfield2 = nil
}

// Field2 returns the field2 value in the mutation.
func (m *TestMutation) Field2() (r float64, exists bool) {
	v := m.field2
	if v == nil {
		return
	}
	return *v, true
}

// OldField2 returns the old field2 value of the Test.
// If the Test object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *TestMutation) OldField2(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldField2 is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldField2 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldField2: %w", err)
	}
	return oldValue.Field2, nil
}

// AddField2 adds f to field2.
func (m *TestMutation) AddField2(f float64) {
	if m.addfield2 != nil {
		*m.addfield2 += f
	} else {
		m.addfield2 = &f
	}
}

// AddedField2 returns the value that was added to the field2 field in this mutation.
func (m *TestMutation) AddedField2() (r float64, exists bool) {
	v := m.addfield2
	if v == nil {
		return
	}
	return *v, true
}

// ResetField2 reset all changes of the "field2" field.
func (m *TestMutation) ResetField2() {
	m.field2 = nil
	m.addfield2 = nil
}

// SetField3 sets the field3 field.
func (m *TestMutation) SetField3(i int32) {
	m.field3 = &i
	m.addfield3 = nil
}

// Field3 returns the field3 value in the mutation.
func (m *TestMutation) Field3() (r int32, exists bool) {
	v := m.field3
	if v == nil {
		return
	}
	return *v, true
}

// OldField3 returns the old field3 value of the Test.
// If the Test object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *TestMutation) OldField3(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldField3 is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldField3 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldField3: %w", err)
	}
	return oldValue.Field3, nil
}

// AddField3 adds i to field3.
func (m *TestMutation) AddField3(i int32) {
	if m.addfield3 != nil {
		*m.addfield3 += i
	} else {
		m.addfield3 = &i
	}
}

// AddedField3 returns the value that was added to the field3 field in this mutation.
func (m *TestMutation) AddedField3() (r int32, exists bool) {
	v := m.addfield3
	if v == nil {
		return
	}
	return *v, true
}

// ResetField3 reset all changes of the "field3" field.
func (m *TestMutation) ResetField3() {
	m.field3 = nil
	m.addfield3 = nil
}

// Op returns the operation name.
func (m *TestMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Test).
func (m *TestMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *TestMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.field1 != nil {
		fields = append(fields, test.FieldField1)
	}
	if m.field2 != nil {
		fields = append(fields, test.FieldField2)
	}
	if m.field3 != nil {
		fields = append(fields, test.FieldField3)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *TestMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case test.FieldField1:
		return m.Field1()
	case test.FieldField2:
		return m.Field2()
	case test.FieldField3:
		return m.Field3()
	}
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *TestMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case test.FieldField1:
		return m.OldField1(ctx)
	case test.FieldField2:
		return m.OldField2(ctx)
	case test.FieldField3:
		return m.OldField3(ctx)
	}
	return nil, fmt.Errorf("unknown Test field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *TestMutation) SetField(name string, value ent.Value) error {
	switch name {
	case test.FieldField1:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetField1(v)
		return nil
	case test.FieldField2:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetField2(v)
		return nil
	case test.FieldField3:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetField3(v)
		return nil
	}
	return fmt.Errorf("unknown Test field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *TestMutation) AddedFields() []string {
	var fields []string
	if m.addfield2 != nil {
		fields = append(fields, test.FieldField2)
	}
	if m.addfield3 != nil {
		fields = append(fields, test.FieldField3)
	}
	return fields
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *TestMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case test.FieldField2:
		return m.AddedField2()
	case test.FieldField3:
		return m.AddedField3()
	}
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *TestMutation) AddField(name string, value ent.Value) error {
	switch name {
	case test.FieldField2:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddField2(v)
		return nil
	case test.FieldField3:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddField3(v)
		return nil
	}
	return fmt.Errorf("unknown Test numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *TestMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *TestMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *TestMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Test nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *TestMutation) ResetField(name string) error {
	switch name {
	case test.FieldField1:
		m.ResetField1()
		return nil
	case test.FieldField2:
		m.ResetField2()
		return nil
	case test.FieldField3:
		m.ResetField3()
		return nil
	}
	return fmt.Errorf("unknown Test field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *TestMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *TestMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *TestMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *TestMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *TestMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *TestMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *TestMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Test unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *TestMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Test edge %s", name)
}
