// Code generated by entc, DO NOT EDIT.

package test

const (
	// Label holds the string label denoting the test type in the database.
	Label = "test"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldField1 holds the string denoting the field1 field in the database.
	FieldField1 = "field1"
	// FieldField2 holds the string denoting the field2 field in the database.
	FieldField2 = "field2"
	// FieldField3 holds the string denoting the field3 field in the database.
	FieldField3 = "field3"

	// Table holds the table name of the test in the database.
	Table = "tests"
)

// Columns holds all SQL columns for test fields.
var Columns = []string{
	FieldID,
	FieldField1,
	FieldField2,
	FieldField3,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
